# Generated by Django 5.2.4 on 2025-07-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'topic'], name='api_subscri_email_b4e2aa_idx')],
                'unique_together': {('email', 'topic')},
            },
        ),
    ]
