# Generated by Django 5.2.4 on 2025-07-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='api_subscri_email_b4e2aa_idx',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['email'], name='api_subscri_email_551944_idx'),
        ),
    ]
